import { CheckCircle2, Clock3, ShieldCheck, UserRound } from "lucide-react";
import { useMemo, useState } from "react";
import { Modal } from "../components/Modal";
import { StatusBadge } from "../components/StatusBadge";
import { useData } from "../hooks/useData";
import { api } from "../lib/api";
import type { Report, Role, User } from "../types";
import { PageError, PageLoading } from "./DashboardPage";

const roles: Role[] = ["CEO", "Developer", "Tester"];

export function UsersPage({ token, currentUser }: { token: string; currentUser: User }) {
  const loader = useMemo(() => async () => { const [users, reports] = await Promise.all([api<User[]>("/users", token), api<Report[]>("/reports", token)]); return { users, reports }; }, [token]);
  const { data, loading, error, reload, setData } = useData(loader, [loader]);
  const [selected, setSelected] = useState<User | null>(null);
  async function changeRole(user: User, role: Role) { const updated = await api<User>(`/users/${user.id}`, token, { method: "PUT", body: { role } }); setData((current) => current ? { ...current, users: current.users.map((item) => item.id === user.id ? updated : item) } : current); }
  if (loading) return <PageLoading />;
  if (error || !data) return <PageError message={error} retry={reload} />;
  return <><div className="page-heading"><div><p className="eyebrow">Personas y permisos</p><h1>Equipo</h1><p className="heading-copy">Carga, progreso y responsabilidades en un solo lugar.</p></div></div><div className="user-grid">{data.users.map((user) => { const assigned = data.reports.filter((report) => report.assignee === user.name); const closed = assigned.filter((report) => ["Solucionado", "Cerrado"].includes(report.status)).length; const percent = assigned.length ? Math.round(closed / assigned.length * 100) : 0; return <article className="user-card user-profile-card" key={user.id}><button className="user-profile-main" type="button" onClick={() => setSelected(user)}><div className="avatar avatar-large">{user.avatar ? <img src={user.avatar} alt=""/> : user.name.slice(0, 1).toUpperCase()}</div><div><h2>{user.name}</h2><span>@{user.username}</span></div><StatusBadge value={user.role}/></button><div className="user-stats"><span><strong>{assigned.length - closed}</strong>abiertos</span><span><strong>{closed}</strong>cerrados</span><span><strong>{percent}%</strong>resolución</span></div><div className="progress-track"><i style={{ width: `${percent}%` }}/></div>{currentUser.role === "CEO" && user.id !== currentUser.id ? <label>Rol<select value={user.role} onChange={(event) => void changeRole(user, event.target.value as Role)} aria-label={`Rol de ${user.name}`}>{roles.map((role) => <option key={role}>{role}</option>)}</select></label> : null}</article>; })}</div><section className="panel permission-panel"><div className="panel-heading"><div><h2>Permisos por rol</h2><p>Una guía clara de quién puede hacer qué.</p></div><ShieldCheck size={19}/></div><div className="permission-grid"><article><strong>CEO</strong><span>Gestiona equipo, etiquetas, responsables y elimina reportes.</span></article><article><strong>Developer</strong><span>Se asigna trabajo, cambia estados y publica parches.</span></article><article><strong>Tester</strong><span>Crea reportes, comenta, adjunta evidencia y sigue actividad.</span></article></div></section>{selected ? <UserProfileModal user={selected} reports={data.reports.filter((report) => report.assignee === selected.name)} onClose={() => setSelected(null)}/> : null}</>;
}

function UserProfileModal({ user, reports, onClose }: { user: User; reports: Report[]; onClose: () => void }) { const closed = reports.filter((report) => ["Solucionado", "Cerrado"].includes(report.status)); const open = reports.filter((report) => !["Solucionado", "Cerrado"].includes(report.status)); return <Modal title={`Perfil de ${user.name}`} onClose={onClose}><div className="profile-modal"><div className="profile-hero"><div className="avatar avatar-large">{user.avatar ? <img src={user.avatar} alt=""/> : user.name.charAt(0)}</div><div><h2>{user.name}</h2><p>@{user.username} · {user.role}</p></div></div><div className="profile-kpis"><span><Clock3 size={17}/><strong>{open.length}</strong>trabajos activos</span><span><CheckCircle2 size={17}/><strong>{closed.length}</strong>resueltos</span><span><UserRound size={17}/><strong>{reports.length}</strong>asignaciones</span></div><section><h3>Trabajo reciente</h3>{reports.length ? reports.slice(0, 8).map((report) => <div className="profile-report" key={report.id}><span><strong>{report.title}</strong><small>{report.id}</small></span><StatusBadge value={report.status}/></div>) : <p className="muted">Todavía no tiene reportes asignados.</p>}</section></div></Modal>; }
